name: CSV scheduled update

on:
  schedule:
  - cron: '0 15 * * 6'
  workflow_dispatch:

jobs:
  update:
    environment: actions
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_ADMIN_TOKEN }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r src/requirements.txt
      - name: Synchronize the csv file with an up-to-date one
        run: |
          cd src
          python download.py
          python csv-json.py "../csv/kdb-$(date +%Y%m%d).csv" list.txt
          cd ..
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        env:
          token: ${{ secrets.GH_ADMIN_TOKEN }}
          title: Sceduled update of syllabus data (${{ steps.date.outputs.date }})
          branch: update_${{ steps.date.outputs.date }}
          author: GitHub Action <action@github.com>
          committer: GitHub Action <action@github.com>
          commit-message: |
            update csv: ${{ steps.date.outputs.date }}
          labels: automated pr
          # delete-branch: true
